// COURSE: CSCI1620
// TERM: FALL 2020
// 
// NAME: Kyle Reestman
// RESOURCES: No outside resources were used in the creation of this enum.

/////////////////////////////////////////////////
//  DO NOT EDIT THIS FILE.  CHANGING THIS CODE
//  IS NOT REQUIRED BY THE ASSIGNMENT.
/////////////////////////////////////////////////

package snake;

/**
 * A simple type to represent the three possible game states in a BrickBreaker
 * game.
 * 
 * <P>THIS ENUM DEFINITION IS PROVIDED AND SHOULD NOT BE EDITED.
 * 
 * @author kreestman
 *
 */
public enum GameState
{
	/**
	 * Represents when the user has lost the game by allow the ball to go off-screen.
	 */
	LOST,
	
	/**
	 * Represents when the user has one the game by breaking all possible bricks. 
	 */
	WON,
	
	/**
	 * Reprsents when the game is still in progress.
	 */
	PLAYING
}
